//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _BLINKY_H_
#define _BLINKY_H_

#include <TinyCLR_Interop.h>


extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Blinky;

#endif  //_BLINKY_H_
